---
- name: Copy private key
  copy:
    src: /home/kubernetes-operator/private-key
    dest: /home/kubernetes-operator/private-key
    force: yes

- name: remove node
  command: bash remove_node.sh
  args:
    chdir: /home/kube/kubernetes-operator/scripts/remove
