apiVersion: apps/v1
kind: Deployment
metadata:
  name: installer-server
  namespace: ecs-system
spec:
  replicas: 2
  selector:
    matchLabels:
      name: installer-server
  template:
    metadata:
      labels:
        name: installer-server
    spec:
      containers:
        - name: installer-server
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
