---
- name: Copy master deploy config 
  copy:
    src: /home/kubernetes-operator/scripts
    dest: /home/kubernetes-operator/
    force: yes

- name: deploy master
  command: bash deploy.sh master
  args:
    chdir: /home/kubernetes-operator/scripts/deploy

