---
#- name: clone deploy script
  #command: git clone https://github.com/gosoon/kubernetes-operator /home/kube/kubernetes-operator
  #ignore_errors: "{{ ignore_assert_errors }}"

- name: Copy master deploy config 
  copy:
    src: /home/kubernetes-operator/scripts
    dest: /home/kubernetes-operator/
    force: yes

- name: deploy master
  command: bash deploy.sh master
  args:
    chdir: /home/kubernetes-operator/scripts/deploy
