---
#- name: Install git cmd
  #command: yum install git -y
  #ignore_errors: "{{ ignore_assert_errors }}"

#- name: clone deploy script
#  command: git clone https://github.com/gosoon/kubernetes-operator /home/kubernetes-operator
#  ignore_errors: "{{ ignore_assert_errors }}"

- name: Copy etcd deploy config 
  file:
    src: /home/kubernetes-operator/scripts
    dest: /home/kubernetes-operator/
    follow: yes
    force: yes

- name: Copy private key
  copy:
    src: /home/kubernetes-operator/private-key
    dest: /home/kubernetes-operator/private-key
    force: yes
    mode: 0600

- name: Deploy etcd
  command: bash deploy.sh etcd
  args:
    chdir: /home/kubernetes-operator/scripts/deploy
